spring:
  application:
    name: vote-service
  profiles:
    active: ${SPRING_PROFILES_ACTIVE:dev}

  config:
    import: optional:file:.env[.properties]

  datasource:
    url: jdbc:mysql://${DB_HOST}/${DB_NAME}?allowPublicKeyRetrieval=true&useSSL=false&characterEncoding=UTF-8
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

jwt:
  secret: ${JWT_SECRET_KEY}
  access-token-expiration: ${JWT_ACCESS_TOKEN_EXPIRATION}
  refresh-token-expiration: ${JWT_REFRESH_TOKEN_EXPIRATION}
  cookie-secure: ${JWT_COOKIE_SECURE}
  refresh-cookie-path: ${JWT_REFRESH_COOKIE_PATH}

swagger:
  server-url: ${SWAGGER_SERVER_URL}
  server-description: ${SWAGGER_SERVER_DESCRIPTION}

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never
      probes:
        enabled: true

springdoc:
  swagger-ui:
    with-credentials: true

server:
  forward-headers-strategy: native
