spring:
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.MySQLDialect
        default_batch_fetch_size: 100
    show-sql: true

jwt:
  secret: "ozlaIbMmUTFPcg-RPMPC9KQZjk8LuGEJZGHcnvqu4wM"
  access-token-expiration: 3600000
  cookie-secure: false



swagger:
  server-url: http://localhost:8080
  server-description: Local Dev Server
