spring:
  application:
    name: vote-service
  profiles:
    active: dev

  datasource:
    url: jdbc:mysql://localhost:3306/vote_service?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    username: vote
    password: vote1234
    driver-class-name: com.mysql.cj.jdbc.Driver